<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE encoder [
<!ELEMENT encoder (extensions,option+)>
<!ATTLIST encoder
  id  CDATA  #REQUIRED
  audio  CDATA  #REQUIRED
  summary  CDATA  #REQUIRED
>
<!ELEMENT extensions (ext+)>
<!ELEMENT ext (#PCDATA)>
<!ATTLIST ext 
  name  CDATA  #REQUIRED
  default  CDATA #IMPLIED
>
<!ELEMENT option (value*)>
<!ATTLIST option 
  param  CDATA  #REQUIRED
  require  CDATA #IMPLIED
>
<!ELEMENT value (#PCDATA)>
]>
<!-- H.264/AVC/MPEG-4 AVC/MPEG-4 Format -->
<encoder id="libx264" audio="libfaac" summary="H.264/AVC/MPEG-4 AVC/MPEG-4 Part 10 Format">
  <extensions>
    <ext name="264">Raw bytestream</ext>
    <ext name="mkv" default="default">Matroska</ext>
    <ext name="flv">Flash Video</ext>
    <ext name="mp4">MP4 (Requires GPAC Support)</ext>
  </extensions>
  <option param="preset">
    <value>ultrafast</value>
    <value>superfast</value>
    <value>veryfast</value>
    <value>faster</value>
    <value>fast</value>
    <value>medium</value>
    <value>slow</value>
    <value>slower</value>
    <value>eryslow</value>
    <value>placebo</value>
  </option>
  <option param="tune">
    <value>film</value>
    <value>animation</value>
    <value>grain</value>
    <value>stillimage</value>
    <value>psnr</value>
    <value>ssim</value>
    <value>fastdecode</value>
    <value>zerolatency</value>
  </option>
  <option param="fastfirstpass" />
  <option param="profile">
    <value>baseline</value>
    <value>main</value>
    <value>high</value>
    <value>high10</value>
    <value>high422</value>
    <value>high444</value>
  </option>
  <option param="x264opts">
    <value>8x8dct</value>
    <value>analyse</value>
    <value>aq</value>
    <value>b_adapt</value>
    <value>b_bias</value>
    <value>bframes</value>
    <value>bluray_compat</value>
    <value>b_pyramid</value>
    <value>cabac</value>
    <value>chroma_me</value>
    <value>chroma_qp_offset</value>
    <value>constrained_intra</value>
    <value>cqm</value>
    <value>crf</value>
    <value>deadzone</value>
    <value>deblock</value>
    <value>decimate</value>
    <value>direct</value>
    <value>fast_pskip</value>
    <value>interlaced</value>
    <value>intra_refresh</value>
    <value>ip_ratio</value>
    <value>keyint_min</value>
    <value>keyint</value>
    <value>mbtree</value>
    <value>me_range</value>
    <value>me</value>
    <value>mixed_ref</value>
    <value>nr</value>
    <value>open_gop</value>
    <value>psy_rd</value>
    <value>psy</value>
    <value>qcomp</value>
    <value>qpmax</value>
    <value>qpmin</value>
    <value>qpstep</value>
    <value>rc_lookahead</value>
    <value>rc</value>
    <value>ref</value>
    <value>scenecut</value>
    <value>sliced_threads</value>
    <value>subme</value>
    <value>trellis</value>
    <value>weightb</value>
    <value>weightp</value>
  </option>
</encoder>
